name: Student Placement MLOps CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  mlops-pipeline:

    runs-on: ubuntu-latest

    # DVC Google Drive authentication
    env:
      GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}

    steps:

      # --------------------------------------------------
      # 1. Checkout repository
      # --------------------------------------------------

      - name: Checkout repository
        uses: actions/checkout@v4

      # --------------------------------------------------
      # 2. Setup Python
      # --------------------------------------------------

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # --------------------------------------------------
      # 3. Install dependencies
      # --------------------------------------------------

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # --------------------------------------------------
      # 4. Pull dataset from DVC
      # --------------------------------------------------

      - name: Pull dataset from DVC
        run: |
          dvc pull

      # --------------------------------------------------
      # 5. Check Python files
      # --------------------------------------------------

      - name: Compile Python files
        run: |
          python -m compileall src

      # --------------------------------------------------
      # 6. Run data validation
      # --------------------------------------------------

      - name: Validate dataset
        run: |
          python src/data/validate.py

      # --------------------------------------------------
      # 7. Run automated ML pipeline
      # --------------------------------------------------

      - name: Run ML pipeline
        run: |
          python src/pipeline.py

      # --------------------------------------------------
      # 8. Check generated model
      # --------------------------------------------------

      - name: Check model artifact
        run: |
          test -f models/placement_pipeline.pkl
          echo "Model artifact exists"

      # --------------------------------------------------
      # 9. Finish
      # --------------------------------------------------

      - name: Pipeline completed
        run: |
          echo "========================================="
          echo " Student Placement MLOps CI PASSED"
          echo "========================================="